In [23]:
import numpy as np

In [24]:
#Make an arry an dpopulate it with random numbers

numbers=np.array([1,5,6,9,10,15,16,33,35])

In [25]:
for element in numbers:
    print(element)

1
5
6
9
10
15
16
33
35


In [26]:
# What if I only want to print >7 aND <20

for element in numbers:
    
    if element>7 and element<20:
        print(element)
    

9
10
15
16


In [27]:
#And if I want to print the edges? say <7 and > 33
for element in numbers:
    
    if element<7 and element>33:
        print(element)
        
#Nothing happens!!!

In [28]:

#And if I want to print the edges? say <7 and > 33
for element in numbers:
    
    if element<7 or element>33:
        print(element)
        
#Nothing happens!!!

1
5
6
35


In [29]:
#What if isntead of looping I want to do it in one go? We can use "bitwise operators

#instead of and use &

numbers>7

array([ True,  True,  True, False, False, False, False, False, False], dtype=bool)

In [30]:
numbers<33

array([False, False, False, False, False, False, False, False,  True], dtype=bool)

In [31]:
#and combine them

(numbers>7) & (numbers<33)

array([False, False, False,  True,  True,  True,  True, False, False], dtype=bool)

In [32]:
#But I actually want to print them out

result = (numbers>7) & (numbers<33)
print(numbers[result])

[ 9 10 15 16]


In [33]:
#What about bitwise or? use | isntead of or

result = (numbers<7) | (numbers>33)
print(numbers[result])

[ 1  5  6 35]
